import * as Notifications from 'expo-notifications';
import * as Device from 'expo-device';
import Constants, { ExecutionEnvironment } from 'expo-constants';
import { Platform } from 'react-native';
import { api } from './api';

const isExpoGo = Constants.executionEnvironment === ExecutionEnvironment.StoreClient;

// Configure foreground notification behavior:
// For incoming push notifications, displayed alert title and body use the already-localized text
// generated by the backend (ai/announce.py via ?lang= header/setting) without re-translating client-side.
Notifications.setNotificationHandler({
  handleNotification: async (notification) => {
    // The backend broadcasts pre-localized announcement text (English / Hindi)
    // based on the device's registered language preference.
    const title = notification.request.content.title;
    const body = notification.request.content.body;
    console.log(`[Push Notification Displayed] Localized Alert Received -> Title: "${title}", Body: "${body}"`);

    return {
      shouldShowAlert: true,
      shouldPlaySound: true,
      shouldSetBadge: true,
      shouldShowBanner: true,
      shouldShowList: true,
    };
  },
});

export async function registerForPushNotificationsAsync(): Promise<string | null> {
  let token: string | null = null;

  if (isExpoGo) {
    console.log('[Push] Running inside Expo Go app. Remote FCM Push Tokens require an EAS Dev Build in SDK 54. Using mock token for app testing.');
    const mockToken = 'mock-expo-go-fcm-token-67890';
    try {
      await api.registerDeviceToken(mockToken, Platform.OS);
    } catch (e) {}
    return mockToken;
  }

  if (!Device.isDevice) {
    console.log('[Push] Must use physical device for Push Notifications. (Using mock token for emulator)');
    return 'mock-emulator-fcm-token-12345';
  }

  try {
    const { status: existingStatus } = await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;

    if (existingStatus !== 'granted') {
      const { status } = await Notifications.requestPermissionsAsync();
      finalStatus = status;
    }

    if (finalStatus !== 'granted') {
      console.warn('[Push] Permission not granted for push notifications.');
      return null;
    }

    const pushTokenData = await Notifications.getDevicePushTokenAsync();
    token = pushTokenData.data;

    // Register token with backend alongside active language
    if (token) {
      await api.registerDeviceToken(token, Platform.OS);
      console.log('[Push] FCM token registered with backend:', token);
    }
  } catch (e) {
    console.warn('[Push] Error getting push token:', e);
  }

  if (Platform.OS === 'android') {
    Notifications.setNotificationChannelAsync('default', {
      name: 'CrowdShield Safety Alerts',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#ef4444',
    });
  }

  return token;
}
